version: "3.6"

volumes:
  postgres_data:

services:
  web: &app
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/app
    ports:
    - published: ${WEB_PORT:-8000}
      target: 8000
    environment: &app_env
      DEBUG: 'True'
