# Generated by Django 2.2.1 on 2019-05-25 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('doors', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('lot', models.CharField(max_length=50)),
            ],
        ),
    ]
